CHAIN_TYPE_BCR_HEAVY = 1
CHAIN_TYPE_BCR_LIGHT_KAPPA = 2
CHAIN_TYPE_BCR_LIGHT_LAMBDA = 3
CHAIN_TYPE_TCR_ALPHA = 4
CHAIN_TYPE_TCR_BETA = 5
#CHAIN_TYPE_TCR_GAMMA = 4
#CHAIN_TYPE_TCR_DETLA = 6

CHAIN_TYPE_2_NAME = {
    CHAIN_TYPE_BCR_HEAVY: "BCR Heavy Chain",
    CHAIN_TYPE_BCR_LIGHT_KAPPA: "BCR Light Chain Kappa",
    CHAIN_TYPE_BCR_LIGHT_LAMBDA: "BCR Light Chain Lambda",
    CHAIN_TYPE_TCR_ALPHA: "TCR Alpha Chain",
    CHAIN_TYPE_TCR_BETA: "TCR Beta Chain",
}

HAS_D = {
    CHAIN_TYPE_BCR_HEAVY: True,
    CHAIN_TYPE_BCR_LIGHT_LAMBDA: False,
    CHAIN_TYPE_BCR_LIGHT_KAPPA: False,
    CHAIN_TYPE_TCR_BETA: True
}
