site_name: GenAIRR Documentation
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - GenAIRR Flow: genairr_flow.md
  - How to Create a Custom DataConfig Instance : custom_data_config.md

theme:
  name: readthedocs
  locale: en
  color_mode: dark
plugins:
    - mkdocs-jupyter