//! Python wrappers for committed event ledger records.

use pyo3::prelude::*;

use crate::event::{EventKind, EventRecord, StateSummary};
use crate::pass::PassEffect;

fn event_kind_name(kind: EventKind) -> &'static str {
    match kind {
        EventKind::PassCommitted => "pass_committed",
    }
}

fn effect_name(effect: &PassEffect) -> String {
    match effect {
        PassEffect::AssignAllele(segment) => format!("assign_allele.{:?}", segment),
        PassEffect::TrimAllele(segment) => format!("trim_allele.{:?}", segment),
        PassEffect::AssembleSegment(segment) => format!("assemble_segment.{:?}", segment),
        PassEffect::AppendRegion(segment) => format!("append_region.{:?}", segment),
        PassEffect::AppendNucleotides => "append_nucleotides".to_string(),
        PassEffect::EditBases => "edit_bases".to_string(),
        PassEffect::StructuralIndel => "structural_indel".to_string(),
    }
    .to_ascii_lowercase()
}

/// Lightweight state shape captured before/after a committed pass.
#[pyclass(name = "StateSummary", module = "GenAIRR._engine", frozen)]
pub struct PyStateSummary {
    inner: StateSummary,
}

impl PyStateSummary {
    pub(crate) fn new(inner: StateSummary) -> Self {
        Self { inner }
    }
}

#[pymethods]
impl PyStateSummary {
    #[getter]
    fn pool_len(&self) -> usize {
        self.inner.pool_len
    }

    #[getter]
    fn region_count(&self) -> usize {
        self.inner.region_count
    }

    #[getter]
    fn assigned_allele_count(&self) -> usize {
        self.inner.assigned_allele_count
    }

    fn __repr__(&self) -> String {
        format!(
            "<StateSummary pool_len={} regions={} assigned_alleles={}>",
            self.inner.pool_len, self.inner.region_count, self.inner.assigned_allele_count
        )
    }
}

/// One committed event generated by the compiled simulator.
#[pyclass(name = "EventRecord", module = "GenAIRR._engine", frozen)]
pub struct PyEventRecord {
    inner: EventRecord,
}

impl PyEventRecord {
    pub(crate) fn new(inner: EventRecord) -> Self {
        Self { inner }
    }
}

#[pymethods]
impl PyEventRecord {
    #[getter]
    fn pass_index(&self) -> usize {
        self.inner.pass_index
    }

    #[getter]
    fn pass_name(&self) -> &str {
        &self.inner.pass_name
    }

    #[getter]
    fn kind(&self) -> &'static str {
        event_kind_name(self.inner.kind)
    }

    /// **Static compile-time effect declarations** (not runtime
    /// consequences). Kept as `effects` on the Python surface for
    /// API stability; the Rust-side field is `compile_effects`.
    /// For the runtime consequence stream see
    /// [`PyEventRecord::simulation_event_count`].
    #[getter]
    fn effects(&self) -> Vec<String> {
        self.inner.compile_effects.iter().map(effect_name).collect()
    }

    #[getter]
    fn trace_start(&self) -> usize {
        self.inner.trace_span.start
    }

    #[getter]
    fn trace_end(&self) -> usize {
        self.inner.trace_span.end
    }

    #[getter]
    fn trace_len(&self) -> usize {
        self.inner.trace_span.len()
    }

    #[getter]
    fn pre(&self) -> PyStateSummary {
        PyStateSummary::new(self.inner.pre)
    }

    #[getter]
    fn post(&self) -> PyStateSummary {
        PyStateSummary::new(self.inner.post)
    }

    /// Number of [`SimulationEvent`]s the pass emitted during commit.
    /// Lightweight Python-side observability for the consequence
    /// channel; full event payload exposure is reserved for a future
    /// slice if/when consumers need it.
    #[getter]
    fn simulation_event_count(&self) -> usize {
        self.inner.simulation_events.len()
    }

    fn __repr__(&self) -> String {
        format!(
            "<EventRecord #{} {} {} trace={}..{}>",
            self.inner.pass_index,
            event_kind_name(self.inner.kind),
            self.inner.pass_name,
            self.inner.trace_span.start,
            self.inner.trace_span.end,
        )
    }
}
